BUGS 

2000-01-14				Jon Kåre Hellan

I have encountered some problems while working on the Python plugin,
which I believe are really symptoms of bugs elsewhere.

1. If init_plugin returns error, plugin_load closes the plugin with
   g_module_close. However, this results in an illegal memory access
   (segfault) inside dlclose. This happened even with a modified
   init_plugin which immediately returned error status, so it's got
   nothing to do with what happens inside init_plugin.

There are lots of missing features, of course.
